// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzJGGR_55M1xMz-YaJvReuxnVvr01ZDAA',
    appId: '1:103267155365:web:75eb07d97a711ec91afc4c',
    messagingSenderId: '103267155365',
    projectId: 'leader-a1c27',
    authDomain: 'leader-a1c27.firebaseapp.com',
    storageBucket: 'leader-a1c27.firebasestorage.app',
    measurementId: 'G-1TPYGDETB1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2vhx9FelDEYKgL9Cn17_6BImzpmMnXRk',
    appId: '1:103267155365:android:f4c397f78a01b39b1afc4c',
    messagingSenderId: '103267155365',
    projectId: 'leader-a1c27',
    storageBucket: 'leader-a1c27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC86HWSt1iFTWbz9T3s3B9PToLVaRfGank',
    appId: '1:103267155365:ios:53f5a74c0e9050b31afc4c',
    messagingSenderId: '103267155365',
    projectId: 'leader-a1c27',
    storageBucket: 'leader-a1c27.firebasestorage.app',
    androidClientId: '103267155365-6589bmm3io15gsgpprb431hgohqr5dbi.apps.googleusercontent.com',
    iosClientId: '103267155365-c44i3och8ier6kdkr61r0ahoh51qk4me.apps.googleusercontent.com',
    iosBundleId: 'com.leadercompany',
  );
}
